import { image, stores, download } from "./components.mjs";
const monthRows = [
  ["January", 6, 5],
  ["February", 2, 1],
  ["March", 2, 2],
  ["April", 5, 5],
  ["May", 0, 0],
  ["June", 3, 3],
  ["July", 5, 5],
  ["August", 1, 1],
  ["September", 4, 4],
  ["October", 6, 6],
  ["November", 2, 2],
  ["December", 4, 4],
];
const formula = (parts) =>
  `<div class="formula">${parts.map((p, i) => `${i ? '<span aria-hidden="true">+</span>' : ""}<div><b>${p[0]}</b><small>${p[1]}</small></div>`).join("")}<span aria-hidden="true">→</span><div class="result"><b>Tuesday</b><small>REMAINDER 2</small></div></div>`;
export const guide = `<div class="wrap"><header class="page-head"><aside class="guide-app-intro"><span class="eyebrow">THE EASIEST WAY TO LEARN</span><p class="guide-app-title">Meet your otter guides in the app.</p><p>Download Otter Day and learn the calendar trick interactively, step by step. Your otter guides will show you how.</p>${stores}</aside><p class="breadcrumb"><a href="/">Otter Day</a> / Calendar guide</p><span class="eyebrow">THE MENTAL CALENDAR GUIDE</span><h1>How to find the weekday<br>of any date.</h1><p class="lead">No magic. Just three small codes and a seven-day loop. Learn the calendar trick, one step at a time.</p><p class="fine">By Felix Plagge · About 8 minutes · Gregorian calendar</p></header><div class="article-layout"><nav class="contents" aria-label="Guide contents"><span class="eyebrow">THE METHOD</span><a href="#big-picture">The big picture</a><a href="#day-code">1. Day code</a><a href="#month-code">2. Month code</a><a href="#year-code">3. Year code</a><a href="#put-together">Put it together</a><a href="#centuries">Centuries &amp; leap years</a><a href="#practice">Try it yourself</a></nav><article class="article">
<section id="big-picture">${image("guide-week", "An otter tutor with a circular instrument: seven nodes for the repeating seven-day week", "guide-image", true, 1200, 800)}<h2>Every seven days,<br>you’re back where you started.</h2><p>A week is a loop. Move forward seven days and the weekday stays the same. Move forward eight days and you advance by just one weekday. That means we can discard complete groups of seven and keep only the remainder.</p><p>The calendar calculation in Otter Day uses this pattern: give the <strong>day, month and year</strong> a code, add the three codes, then take the remainder after division by seven. Match it to a weekday:</p><div class="code-strip" role="img" aria-label="Monday 1, Tuesday 2, Wednesday 3, Thursday 4, Friday 5, Saturday 6, Sunday 0">${["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d, i) => `<div><strong>${(i + 1) % 7}</strong><span>${d}</span></div>`).join("")}</div><p>Sunday has code <strong>0</strong>. A total of 7, 14 or 21 therefore means Sunday too. The visual week starts on Monday; the calculation still uses Sunday as zero.</p><div class="note"><p><strong>One example all the way through:</strong> September 22, 2026. We’ll turn it into three codes, then discover its weekday.</p></div></section>
<section id="day-code"><span class="eyebrow">01 / THE DAY</span><h2>Keep what’s left after seven.</h2><p>Take the day of the month and remove complete groups of seven. For the 22nd, subtract 21. The remainder is <strong>1</strong>, so the day code is 1.</p><div class="formula" role="img" aria-label="22 minus 21 equals 1"><div><b>22</b><small>DAY OF MONTH</small></div><span>−</span><div><b>21</b><small>THREE WEEKS</small></div><span>=</span><div class="result"><b>1</b><small>DAY CODE</small></div></div><p>More examples: the 7th has code 0; the 15th has code 1; the 31st has code 3. You can also leave the day unreduced and remove the sevens at the end. Small numbers are usually easier in your head.</p></section>
<section id="month-code"><span class="eyebrow">02 / THE MONTH</span><h2>Twelve months.<br>Twelve little shortcuts.</h2><p>Each month has a code. These account for where the month starts in the year. Learn the ordinary-year column first. Only January and February change in a leap year.</p><table class="code-table"><caption class="sr-only">Otter Day month codes</caption><thead><tr><th scope="col">Month</th><th scope="col">Ordinary year</th><th scope="col">Leap year</th></tr></thead><tbody>${monthRows.map(([m, c, l]) => `<tr><th scope="row">${m}</th><td>${c}</td><td>${l}</td></tr>`).join("")}</tbody></table><p>For our example, <strong>September has code 4</strong>. Notice the shared codes: February, March and November use 2 in an ordinary year; April and July use 5; October and January use 6.</p><p>Practice recalling the codes before trying to calculate whole dates. In the app, Month Codes practice lets you rehearse this part on its own.</p></section>
<section id="year-code"><span class="eyebrow">03 / THE YEAR</span><h2>A small sum for the year.</h2><p>For years from 2000 to 2099, take the last two digits. Add the number of complete groups of four in those digits. Then keep the remainder after division by seven.</p><p>For <strong>2026</strong>: take 26. There are six complete groups of four in 26, so add 6. That gives 32. Remove 28, leaving <strong>year code 4</strong>.</p><div class="formula" role="img" aria-label="26 plus 6 equals 32, remainder 4"><div><b>26</b><small>LAST TWO DIGITS</small></div><span>+</span><div><b>6</b><small>26 ÷ 4, ROUNDED DOWN</small></div><span>→</span><div class="result"><b>4</b><small>32 MINUS 28</small></div></div><p>Within the same year, this code stays the same. That is why starting with dates in the current year makes the method much easier to practise. Other centuries need one extra adjustment, explained below.</p></section>
<section id="put-together"><span class="eyebrow">THE LIGHT-BULB MOMENT</span><h2>Three codes. One weekday.</h2><p>For <strong>September 22, 2026</strong>, add day code 1, month code 4 and year code 4. The total is 9. Remove 7 and you have 2: <strong>Tuesday</strong>.</p>${formula(
  [
    [1, "DAY"],
    [4, "MONTH"],
    [4, "YEAR"],
  ],
)}<p>That’s the whole trick. The work is in recognizing the codes quickly, not memorizing thousands of dates.</p></section>
<section id="centuries"><span class="eyebrow">A WIDER TIME WINDOW</span><h2>Other centuries.<br>The same method.</h2><p>When calculating the year code, add the century code <em>before</em> reducing the sum by seven:</p><div class="note"><p><strong>Year code =</strong> last two digits + complete groups of four + century code. Keep the remainder after division by seven.</p></div><table class="code-table"><caption class="sr-only">Century codes for levels one through six</caption><thead><tr><th scope="col">Century</th><th scope="col">Code</th></tr></thead><tbody><tr><th scope="row">1700–1799</th><td>5</td></tr><tr><th scope="row">1800–1899</th><td>3</td></tr><tr><th scope="row">1900–1999</th><td>1</td></tr><tr><th scope="row">2000–2099</th><td>0</td></tr></tbody></table><p>These codes repeat every 400 years: the 2100s use 5, the 2200s use 3, the 2300s use 1 and the 2400s use 0.</p><h3>A historical example</h3><p><strong>July 4, 1776:</strong> day code 4, July code 5. The year calculation is 76 + 19 + 5 = 100, whose remainder is 2. Add 4 + 5 + 2 = 11. Remainder 4 means <strong>Thursday</strong>.</p><h3>Remember the leap-year adjustment</h3><p>A Gregorian leap year is divisible by 4, except years divisible by 100 are ordinary years unless also divisible by 400. So 2024 and 2000 are leap years; 1900 and 2100 are not.</p><p>In a leap year, use <strong>January code 5</strong> and <strong>February code 1</strong>. From March onward, use the usual codes. Do not subtract another point elsewhere.</p><p><strong>February 29, 2024:</strong> day code 1, leap-February code 1, year code (24 + 6) mod 7 = 2. Add 1 + 1 + 2 = 4: <strong>Thursday</strong>.</p><div class="note"><p><strong>A note about history:</strong> countries adopted the Gregorian calendar at different times. This method extends Gregorian rules backwards; it does not convert a historical local Julian date.</p></div></section>
<section id="practice"><span class="eyebrow">MAKE IT YOURS</span><h2>Start slow. Let it click.</h2><ol><li>Learn the weekday codes and practise removing sevens.</li><li>Learn the month codes a few at a time.</li><li>Stay within one year, so you can reuse its year code.</li><li>Expand into other years and centuries when answers feel reliable.</li><li>Work on speed last. Five seconds is a goal to practise toward, not a deadline.</li></ol><h3>Check your calculation</h3><p>Work it out first, then compare your three codes below. The checker uses the same method as the app.</p><form class="calculator" data-calculator><label for="check-date">Choose a Gregorian date</label><input type="date" id="check-date" min="1700-01-01" max="2099-12-31" value="2026-09-22" required><button class="button" type="submit" disabled>Check my date →</button><output for="check-date" aria-live="polite">1 + 4 + 4 = 9. Remainder 2 → Tuesday.</output><noscript><p>The interactive checker requires JavaScript. All examples and code tables above work without it.</p></noscript></form><p style="margin-top:26px">Prefer learning by playing? Otter Day’s guided tutorials, six levels and Speed Academy turn these steps into practice. Or <a href="/#try">try a sample date right now</a>.</p><p>More questions? See the <a href="/faq/">calendar game FAQ</a>, including how this method differs from the Doomsday algorithm.</p></section>
</article></div></div>${download}`;
